Update Python_CheatSheet.md with two new commands
Jahenr/CheatSheets pull request #44
Opened 2022-10-02 09:53 UTC by prabhav5112

2022-10-04 21:00 UTC, Jahenr requested changes

2022-10-04 21:00 UTC, Jahenr commented on Python_CheatSheet.md
> +        lst.sort(key = lambda x : x[i])
Same with this one too please.

2022-10-04 21:02 UTC, Jahenr commented
Hi prabhav5112

Thank you for the contribution, please review the comments then I can get that merged for you. 👍🏿

2022-10-05 02:24 UTC, prabhav5112 commented
Resolved the indentation for both commands

2022-10-05 15:45 UTC, Jahenr commented
Thank you, it looks good. I appreciate the help, take care 👍🏿

2022-10-05 15:45 UTC, merged